#!/usr/bin/env python3
"""Generate a ~100MB-class heavy page for Phase 3.9 resource testing.

The page models large/complex real-world sites:
  - a large DOM (default 2000 nodes with text content),
  - N noise PNGs (512x512 by default) whose DECODED size dominates RSS
    (512*512*4 = 1 MB per image decoded; 100 images ~= 100 MB),
  - inline CSS/JS so the only network weight is HTML + images.

Output: /tmp/heavy_site/  (NOT committed — generated)
Serve:  python3 -m http.server 8125 --directory /tmp/heavy_site
"""
import argparse
import os
import random
import zlib
import struct
import pathlib


def png_chunk(kind: bytes, data: bytes) -> bytes:
    return (struct.pack(">I", len(data)) + kind + data
            + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF))


def noise_png(w: int, h: int, seed: int) -> bytes:
    rng = random.Random(seed)
    # Row-major RGBA noise, but compressible: random per 16px block base
    # color + small per-pixel jitter (realistic photo-like entropy).
    raw = bytearray()
    blocks_x = (w + 15) // 16
    bases = [[(rng.randrange(256), rng.randrange(256), rng.randrange(256))
              for _ in range(blocks_x)] for _ in range((h + 15) // 16)]
    for y in range(h):
        raw.append(0)  # filter: none
        by, bx = y // 16, 0
        for x in range(w):
            bx = x // 16
            r, g, b = bases[by][bx]
            raw += bytes(((r + rng.randrange(8)) & 0xFF,
                          (g + rng.randrange(8)) & 0xFF,
                          (b + rng.randrange(8)) & 0xFF, 255))
    ihdr = struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0)
    idat = zlib.compress(bytes(raw), 6)
    return (b"\x89PNG\r\n\x1a\n" + png_chunk(b"IHDR", ihdr)
            + png_chunk(b"IDAT", idat) + png_chunk(b"IEND", b""))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="/tmp/heavy_site")
    ap.add_argument("--images", type=int, default=100)
    ap.add_argument("--dom-nodes", type=int, default=2000)
    ap.add_argument("--img-size", type=int, default=512)
    args = ap.parse_args()

    out = pathlib.Path(args.out)
    (out / "img").mkdir(parents=True, exist_ok=True)

    total_png = 0
    for i in range(args.images):
        data = noise_png(args.img_size, args.img_size, seed=i + 1)
        (out / "img" / f"img{i:03d}.png").write_bytes(data)
        total_png += len(data)

    sections = []
    for i in range(args.dom_nodes // 10):
        sections.append(f"""
  <section class="row">
    <h3>Section {i}: polyfill content block</h3>
    {''.join(f'<p>Paragraph {i}.{j} — the quick brown fox jumps over the lazy '
             f'dog while rendering engines trade memory for speed.</p>' for j in range(9))}
  </section>""")
    body = "\n".join(sections)

    imgs = "\n".join(
        f'<img loading="eager" src="img/img{i:03d}.png" alt="asset {i}">'
        for i in range(args.images))

    (out / "index.html").write_text(f"""<!DOCTYPE html>
<!-- Phase 3.9 heavy-page fixture. Generated by scripts/gen_heavy_page.py.
     DOM nodes ~= {args.dom_nodes}, images = {args.images} x {args.img_size}^2
     (decoded ~= {args.images * args.img_size * args.img_size * 4 // (1024*1024)} MB). -->
<html><head><meta charset="utf-8"><style>
body {{ font: 14px/1.4 sans-serif; margin: 12px; background: #f2f4f7; }}
img {{ width: 128px; height: 128px; margin: 2px; border-radius: 4px; }}
.row {{ background: #fff; border: 1px solid #dde; border-radius: 6px;
        padding: 8px 12px; margin: 8px 0; }}
h1 {{ font-size: 18px; }}
</style></head><body>
<h1>brows12 Phase 3.9 heavy page — {args.images} images / {args.dom_nodes} nodes</h1>
{imgs}
{body}
</body></html>""")

    html_kb = (out / "index.html").stat().st_size / 1024
    decoded_mb = args.images * args.img_size * args.img_size * 4 / (1024 * 1024)
    print(f"heavy site at {out}: html={html_kb:.0f}KB "
          f"pngs={total_png/1048576:.1f}MB decoded~{decoded_mb:.0f}MB "
          f"dom_nodes~{args.dom_nodes}")


if __name__ == "__main__":
    main()
