#!/usr/bin/env python3
"""Regenerate fixtures/phase3/wasm.html with a byte-exact hand-assembled
WASM module (sections sized programmatically so the fixture never has a
malformed module)."""
import pathlib

def leb(n: int) -> bytes:
    out = bytearray()
    while True:
        b = n & 0x7F
        n >>= 7
        if n:
            out.append(b | 0x80)
        else:
            out.append(b)
            return bytes(out)

def section(sid: int, payload: bytes) -> bytes:
    return bytes([sid]) + leb(len(payload)) + payload

def name(s: str) -> bytes:
    b = s.encode()
    return leb(len(b)) + b

# ---- types ----
# 0: (i32,i32)->i32   1: (i64,i64)->i64   2: ()->()   3: ()->i32
types = leb(4) + b"\x60\x02\x7f\x7f\x01\x7f" + b"\x60\x02\x7e\x7e\x01\x7e" \
        + b"\x60\x00\x00" + b"\x60\x00\x01\x7f"

# ---- functions: func0=t0 add, func1=t1 mul64, func2=t2 noop, func3=t3 store_get ----
funcs = leb(4) + b"\x00\x01\x02\x03"

# ---- memory: min 1 ----
mem = leb(1) + b"\x00\x01"

# ---- exports ----
exports = leb(5)
exports += name("add") + b"\x00" + leb(0)
exports += name("mul64") + b"\x00" + leb(1)
exports += name("noop") + b"\x00" + leb(2)
exports += name("mem") + b"\x02" + leb(0)
exports += name("store_get") + b"\x00" + leb(3)

# ---- code bodies ----
def body(locals_count: int, code: bytes) -> bytes:
    content = leb(locals_count) + code
    return leb(len(content)) + content

add_body   = body(0, b"\x20\x00\x20\x01\x6a\x0b")           # l0 l1 i32.add end
mul64_body = body(0, b"\x20\x00\x20\x01\x7e\x0b")           # l0 l1 i64.mul end
noop_body  = body(0, b"\x0b")                                # end
# i32.const 0; i32.const 1234; i32.store; i32.const 0; i32.load; end
store_body = body(0, b"\x41\x00\x41\xd2\x09\x36\x02\x00\x41\x00\x28\x02\x00\x0b")
code = leb(4) + add_body + mul64_body + noop_body + store_body

module = (b"\x00\x61\x73\x6d\x01\x00\x00\x00"
          + section(1, types) + section(3, funcs) + section(5, mem)
          + section(7, exports) + section(10, code))

# sanity: decode with python wasm runtime if available
try:
    import wasmtime  # noqa
    store = wasmtime.Store()
    m = wasmtime.Module(store.engine, module)
    print("wasmtime validation OK")
except ImportError:
    print("wasmtime not installed; structural self-check only")

# structural self-check: re-walk section sizes
off = 8
while off < len(module):
    sid, size = module[off], 0
    shift, i = 0, 0
    while True:
        b = module[off + 1 + i]
        size |= (b & 0x7F) << shift
        shift += 7
        i += 1
        if not (b & 0x80):
            break
    end = off + 1 + i + size
    assert end <= len(module), f"section {sid} overruns module"
    print(f"section {sid}: size {size} ok")
    off = end

b64 = __import__("base64").b64encode(module).decode()

TEMPLATE = """<!DOCTYPE html>
<!-- Phase 3.8 fixture: WebAssembly — hand-assembled minimal module
     (i32 add, i64 mul, memory, store/load), sync & async instantiate,
     memory.grow. Bytes generated by scripts/gen_wasm_fixture.py. -->
<html>
<head>
<meta charset="utf-8">
<style>
  body { font: 14px/1.4 sans-serif; margin: 14px; background: #f4f6f9; }
  h1 { font-size: 18px; margin: 0 0 6px; }
  #report { background: #fff; border: 1px solid #ccd; padding: 8px 12px;
            font: 13px monospace; white-space: pre; }
</style>
</head>
<body>
<h1>WebAssembly — instantiate, exports, memory</h1>
<pre id="report">running…</pre>

<script>
const R = [];
function check(n, c) { R.push((c ? "PASS" : "FAIL") + "  " + n); }
const bytes = Uint8Array.from(atob("__B64__"), c => c.charCodeAt(0));

async function run() {
  try {
    check("WebAssembly global exists", typeof WebAssembly === "object");
    check("Module.validate", WebAssembly.validate(bytes.buffer));
    const mod = await WebAssembly.instantiate(bytes.buffer);
    const ex = mod.instance.exports;
    check("instantiate(bufferSource)", !!ex);
    check("add(40, 2) === 42", ex.add(40, 2) === 42);
    check("add(-5, 7) === 2", ex.add(-5, 7) === 2);
    check("mul64(3000000n, 1000000n) === 3e12",
          ex.mul64(3000000n, 1000000n) === 3000000000000n);
    check("memory exported, 1 page (64KiB)", ex.mem instanceof WebAssembly.Memory
          && ex.mem.buffer.byteLength === 65536);
    check("memory store/load round-trip", ex.store_get() === 1234);
    const sync = new WebAssembly.Instance(new WebAssembly.Module(bytes.buffer));
    check("sync compile path", sync.exports.add(1, 1) === 2);
    const oldPages = ex.mem.buffer.byteLength;
    check("memory.grow(+1)", ex.mem.grow(1) === 1 &&
          ex.mem.buffer.byteLength === oldPages + 65536);

    const pass = R.filter(l => l.startsWith("PASS")).length;
    const el = document.getElementById("report");
    el.textContent = "RESULT: " + pass + "/" + R.length + "\\n" + R.join("\\n");
    el.style.background = pass === R.length ? "#d8ffd8" : "#ffd8d8";
    document.title = pass === R.length ? "PASS" : "FAIL";
  } catch (err) {
    R.push("FAIL  exception: " + err.message);
    document.getElementById("report").textContent = R.join("\\n");
    document.title = "FAIL";
  }
}
run();
</script>
</body>
</html>
"""

out = pathlib.Path("/home/z/my-project/brows12-v2/fixtures/phase3/wasm.html")
out.write_text(TEMPLATE.replace("__B64__", b64))
print(f"wrote {out} ({len(module)} bytes module, {len(b64)} b64)")
